import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Bank Indicators</title>
        <meta name="description" content="Generated by Open Bank Indicators" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
        TODO
        </h1>
      </main>

      <footer className={styles.footer}>
        TODO
      </footer>
    </div>
  )
}

export default Home
